### ISSUE TITLE
Terkait pencantuman vexagame.com di footer

### ISSUE THREAD

**Issue by samsulmaarif** [yogs22/mini-medium#5]
Saya mau tanya, terkait pencantuman tersebut. Apakah mandatory? 

Misal, kontennya saya ubah dengan lorem-ipsum apakah itu masih wajib dicantumkan? 

Terima kasih. 

terkait #1

**Comment by yogs22** [comment]
Untuk konten vexagame.com tersebut bebas dirubah karna hanya sekedar layouting
